apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cyber-news-alert
resources:
- ../../base
generators:
- secret-generator.yaml
images:
- name: ghcr.io/giacometti-r/projecteagleeye
  newName: ghcr.io/giacometti-r/projecteagleeye
  newTag: 6c8498c783b0612069eb6547ab06dc18bd149d89
