apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cyber-news-alert
resources:
  - ../../base
  - secret-generator.yaml
images:
  - name: ghcr.io/giacometti-r/projecteagleeye
    newTag: latest
