apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cyber-news-alert
resources:
- ../../base
generators:
- secret-generator.yaml
images:
- name: ghcr.io/giacometti-r/projecteagleeye
  newName: ghcr.io/giacometti-r/projecteagleeye
  newTag: 700d9c048fdc23cfe8558574d808006b771e93f3
