# Replace every CHANGE_ME value, update .sops.yaml with your age public key,
# then encrypt this file before enabling Argo CD sync:
#   sops --encrypt --in-place k8s/overlays/prod/secrets.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cyber-news-alert-secrets
type: Opaque
stringData:
    SMTP_HOST: ENC[AES256_GCM,data:vB4Aho8Pde8TRPqLvBE=,iv:gG9qC/DbxJ8WetKxutUXG268ha5z3zkK7pNbzy0ApRs=,tag:0TkbH1OXxf+VjpYmjqhP2w==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:YbOR,iv:MlGYPKxFg9UI7KvVln1imjkV8zY0Qzo1Idvjyed4H7M=,tag:n7X4hD0xzzJjLK9HiJ+ZXw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:wYkeYjwcgnr+Vb8LlRa3QULi8crCFEKTNmOP,iv:X7Zwh5NrLh6iyJKPcNdLeocu2wQWU7EW1dXSM1hjlq0=,tag:u970i0w+ttKCSEoowznOEw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:DxUPCJsJLTgmbrur5VD/sA==,iv:AEZxFdRKfG06wbBfsuPFTGIrRbztGFsqSMB5TI4NbY4=,tag:i6qbtWo3l6fHWWjXRRFNoA==,type:str]
    SENDER_EMAIL: ENC[AES256_GCM,data:ws1NjLnj6w2AT44DQz9J+sawL5ESMgA9xeyd,iv:EODikNyOqAv+MmbyEwNhhw23T3Uqd5rEljKAfOgGf4Q=,tag:grw2VImkIwptesY33ttYOw==,type:str]
    RECIPIENT_EMAIL: ENC[AES256_GCM,data:r/xDEBYZHY7rgw/vrAT/l8oAlW3Ut+FasUDY,iv:bTsuuuOtbuWb17XoeM1VNTUXZJcZcAUjc9cz4IJzmNs=,tag:q/CAb04toJwesVLvnE6fkA==,type:str]
    DIGEST_RECIPIENT_EMAIL: ENC[AES256_GCM,data:WtryvFzhrWhILadMtomniyBjze7qsi91Plfk,iv:LEJNpL3jq//dpV0zlxm3Ucg+YEtiWsooXgWYLV/rDEk=,tag:qItzWTTTtzyr187L5SxjkA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:X7v7wF3TaIvNwHJlae4ldA==,iv:w7DahnCR3eQb+iRFm2AdQTs0yVG79M8EG3MH2o8XAmE=,tag:pMgXpW56OAfSE+0QjTJS6Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ajUZG7f4k5gdMWOUxZ8sZ6sYSs6OPrkei2BcgcJWfVYvyOsI2Clk6zFGnUYtsVWakw0WtJ4KZVGoB+gGAokGUEaq1no=,iv:vQQwxYhxv+hqL7SAxh9bxURo2SUvyjYQPedzAnU7uF4=,tag:/p6E1jY7W//X0GRAFAzz9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbW5lTGVvQjBpNFJjV2ps
            RTd6a3Z0dTZqNSt3SjkrZHFOTjJhNmNUTWhRCm9wTDFhTFdkT1lFeTFKWkF6R1Qr
            cFhuT2VoVVlBY2lBaUZKNzhDemxobUUKLS0tIDRWQm5xcWN1U2xJcHR5TDJ6eDRL
            SFFLVW9oUDA2MVFXeDZtNUxkMTRobkEKEkrPV15aCF6kOr4cCjTpydS+d8r42RMD
            nasxUbbpZN2IZNIKYNC43QXmXkmpALbvYnfYNziGmvG74qMF8P4GNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158n6phchcwrszh07a3s0g43nd5y85e9p0xpv4amnrp6fm2uftsjqx3zw9l
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-06-04T17:27:33Z"
    mac: ENC[AES256_GCM,data:ebVaA/G6yQibwKGWNBqBmEB7YiudXOJEPz4bzJrQOXtUJPsVD2lAZA6YJrGzaGLXspJtozjxM5C/N4UIsVJdD4tNiMWAkHOyBYUl51P63YIKLUuoFtoeKNYZ8276Y48Ry1c+GbOwaMP68/SKwYXz/VX1upD9LWbLRyPyWQ/P/fo=,iv:drOP2qTSFiAOOPwgzAT8nXdOuZzPvGIDOsuEzZUdzP8=,tag:ajWSHks+bm//QxJG7jO1HQ==,type:str]
    version: 3.13.1
