# Replace every CHANGE_ME value, update .sops.yaml with your age public key,
# then encrypt this file before enabling Argo CD sync:
#   sops --encrypt --in-place k8s/overlays/prod/secrets.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cyber-news-alert-secrets
type: Opaque
stringData:
    SMTP_HOST: ENC[AES256_GCM,data:Oqg0Qng6p7pP1Iimdv0=,iv:VLiMPFkO+Mg6qnpPxbObY1/Ojr+Lxs5C+Ntz1o4Vf/U=,tag:2rKbi990mcbIFQKH2QW7fA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:BPxw,iv:WxPrqT9gzxzewcZlulTUFSpHpeIV/Tnr0ME4KkCW+zM=,tag:QwciW5e3GXg7Ua950GTNYg==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:95+J0HhIzPmv+4vmIYOdHIyzm4uD+DcYLv40,iv:og7lLORQBA1Bk2h+HjF1npwrs3sRrBlUcRjTgNy5CII=,tag:p9yJvEJ/blqX6NUtpOcqQQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:L4NafvbGjFDOFa8Tj2E1EQ==,iv:gleAAe1U9Mxba6c39BI4rSA03KzUmupLTf/h7A8fQC0=,tag:kL6YmBhI7/IV7X9NOKurPw==,type:str]
    SENDER_EMAIL: ENC[AES256_GCM,data:XL9PFodxexTHcXth3+rcx6n4Azdb4N5lM2Z4,iv:sGs+evSYhmAZqcJqhxJf5GitcGUeYpsPSPCip2OhBwo=,tag:ICzJEPaZq6G90VWRsYZ/GA==,type:str]
    RECIPIENT_EMAIL: ENC[AES256_GCM,data:n42KTgxpV3LN50U7UxCPUToVXkj8leBRt46e,iv:6xbsP0Bo6HFPGg++5dLTrCfRgbmOJOWYkdWdES0UR6k=,tag:W8MwWl4mueXfbt1JG2QSDA==,type:str]
    DIGEST_RECIPIENT_EMAIL: ENC[AES256_GCM,data:18WBWODWBTAlgOyWATlmMCDaMF4ho364uz+T,iv:vybzdMmBpAq1fXa+Z6qTrBdTeIMFebeC42AyYK2BbBE=,tag:RGRspg/o4KdKy4ebycc6rg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:p16eN2Opm/yxl/GnEEqPvg==,iv:PRrNao4036XAuKbA1xcua7arbaVfEUF+nSfcuFweB8Y=,tag:VEMl2R6Wcfn0kI1tqoXMgg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:INX3OBQKk+0rj2XVV/CU/tUr+Blr4GwpXOrBmEcMb9cJ//48ryq7HQYhSV8kUNup8+PgpZQDwM3digkJdcRdvgweAFc0M6n34IQ=,iv:SoAIkIftSHEGveH4O9svq6C6saMKsj1rD1vcJBozIyQ=,tag:iQWFVja3yVV8Svc9fMiP0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVFlUbUM0SlBoOUR0dW5k
            ZnlLbHp3VG9QeHNiNW5yQlVMaFEyTjFwdTJjCno4RTgrdGE5dCtIN1FMVmRYU0pw
            SFJ2eFVobStZTStVYzExeXNSTk0xOU0KLS0tIFpuS1F5RWoyUWF0YWhUV2t3c3JC
            VDBkYjVOcHlTY0p4WXlJYU9mNUJycDQKRx24YKtBFYpr/9ViW8+2SEzzpkQXL4pL
            dAwRPfwt3jIUOLZaxF13VqfafUiz2liDqKCxAxP3tSKi3Ykk2tbETg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age158n6phchcwrszh07a3s0g43nd5y85e9p0xpv4amnrp6fm2uftsjqx3zw9l
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-06-06T14:08:13Z"
    mac: ENC[AES256_GCM,data:8+HbN0ratNbJSOkE3SoG+08BqbsR2ITswWiccW1NBn9Ep+pWX9W4cx1RDzy4mS2JnTaC+FYAvjkn62ukEwUIwm6PfGo4TVomfh1/so9Xiv+/oBl0fpq0LZevMZ0nzGEgq+Sq5y8GP4XfDZ65QKQnDUhKXv7fpG5QWl/9PjrAl5Q=,iv:DYer0eRZJQpkqMxfRUF9KV/220acsqQ1xr3DtorgmKM=,tag:lXeCix60zpACAEgkBFloeg==,type:str]
    version: 3.13.1
