apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cyber-news-alert
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - cronjob.yaml
